export const club = [
    {id: "1", 
    img: "https://brandlogos.net/wp-content/uploads/2017/05/manchester-city-fc-logo-512x512.png",
    name: "Man City", match: 33, point: 76,},
    {id: "2", 
    img: "https://brandlogos.net/wp-content/uploads/2015/10/arsenal-fc-logo-512x512.png",
    name: "Arsenal", match: 34, point: 77,},
    {id: "3", 
    img: "https://brandlogos.net/wp-content/uploads/2021/04/manchester-united-logo-512x512.png",
    name: "Man Utd", match: 33, point: 53,},
    {id: "4", 
    img: "https://brandlogos.net/wp-content/uploads/2014/10/liverpool_fc-logo_brandlogos.net_vfw8i-512x671.png",
    name: "Liverpool", match: 34, point: 74,},
    {id: "5", 
    img: "https://brandlogos.net/wp-content/uploads/2011/08/chelsea-logo-vector.png",
    name: "Chelsea", match: 32, point: 47,},
    {id: "6", 
    img: "https://brandlogos.net/wp-content/uploads/2014/10/newcastle-united-logo-preview-400x400.png",
    name: "Newcastle", match: 33, point: 50,},
    {id: "7",
    img: "https://brandlogos.net/wp-content/uploads/2018/09/brighton-hove-albion-logo-512x512.png",
    name: "Brighton", match: 33, point: 44,},
    {id: "8", 
    img: "https://brandlogos.net/wp-content/uploads/2016/11/everton-fc-logo-preview-400x400.png",
    name: "Everton", match: 34, point: 33,},
    {id: "9", 
    img: "https://brandlogos.net/wp-content/uploads/2014/10/tottenham-hotspur-fc-logo.png",
    name: "Tottenham", match: 32, point: 60,},
    {id: "10", 
    img: "https://brandlogos.net/wp-content/uploads/2014/09/aston-villa-logo-512x512.png",
    name: "Aston Villa", match: 34, point: 66,},
];